import {
  School,
  NewsArticle,
  CalendarEvent,
  BoardMember,
  LeadershipMember,
  Job,
  Testimonial,
  Sport,
  AcademicProgram,
  DistrictStats,
  NavItem,
} from '@/types';

// Real District Statistics from FCS Website
export const districtStats: DistrictStats = {
  totalStudents: 54000,
  totalSchools: 42, // 23 elementary, 11 middle, 8 high schools
  graduationRate: 95.8,
  collegeReadinessRate: 89.5,
  apPassRate: 78.3,
  teacherStudentRatio: 15,
  averageClassSize: 22,
  totalTeachers: 3600,
};

// District facts from official website
export const districtFacts = {
  countries: 129, // Students from 129 different countries
  languages: 69, // Supporting 69 languages
  enrollmentGrowth: 40, // 40% enrollment increase in past decade
};

// Navigation Items
export const navigationItems: NavItem[] = [
  {
    title: 'Schools',
    href: '/schools',
    description: 'Explore our 42 world-class schools',
    children: [
      { title: 'Find a School', href: '/schools', description: 'Browse all schools by level' },
      { title: 'Elementary Schools', href: '/schools?level=elementary', description: '24 elementary schools' },
      { title: 'Middle Schools', href: '/schools?level=middle', description: '10 middle schools' },
      { title: 'High Schools', href: '/schools?level=high', description: '8 high schools' },
      { title: 'School Locator', href: '/schools/locator', description: 'Find your zoned school' },
    ],
  },
  {
    title: 'Academics',
    href: '/academics',
    description: 'Excellence in education',
    children: [
      { title: 'Programs Overview', href: '/academics', description: 'All academic programs' },
      { title: 'AP & IB Programs', href: '/academics/ap-ib', description: 'Advanced placement' },
      { title: 'STEM Education', href: '/academics/stem', description: 'Science & technology' },
      { title: 'Fine Arts', href: '/arts', description: 'Music, theater & visual arts' },
      { title: 'Career Pathways', href: '/academics/careers', description: 'College & career ready' },
    ],
  },
  {
    title: 'Athletics',
    href: '/athletics',
    description: 'Championship programs',
  },
  {
    title: 'News',
    href: '/news',
    description: 'Latest updates & announcements',
  },
  {
    title: 'Calendar',
    href: '/calendar',
    description: 'Events & important dates',
  },
  {
    title: 'About',
    href: '/about',
    description: 'Our mission & leadership',
    children: [
      { title: 'Our District', href: '/about', description: 'History & mission' },
      { title: 'Board of Education', href: '/board', description: 'Meet the board' },
      { title: 'Leadership', href: '/about/leadership', description: 'District leadership team' },
      { title: 'Careers', href: '/careers', description: 'Join our team' },
      { title: 'Contact', href: '/contact', description: 'Get in touch' },
    ],
  },
];

// Schools Data - All 42 Forsyth County Schools (Real Data from Official Sources)
export const schools: School[] = [
  // HIGH SCHOOLS (8 schools)
  {
    id: 'fchs',
    slug: 'forsyth-central-high-school',
    name: 'Forsyth Central High School',
    level: 'high',
    address: '520 Tribble Gap Road',
    city: 'Cumming',
    state: 'GA',
    zip: '30040',
    phone: '(770) 887-8151',
    website: 'https://fchs.forsyth.k12.ga.us',
    enrollment: 2450,
    rating: 4.5,
    principal: {
      name: 'Tracey Winkler',
      title: 'Principal',
      email: 'twinkler@forsyth.k12.ga.us',
      phone: '(770) 887-8151',
      image: '/images/principals/tracey-winkler.jpg',
    },
    heroImage: '/images/schools/fchs-hero.jpg',
    mascot: 'Bulldogs',
    colors: ['#C8102E', '#000000'],
    established: 1956,
    latitude: 34.2073,
    longitude: -84.1380,
    description: 'Forsyth Central High School is the flagship high school of Forsyth County, offering exceptional academics, championship athletics, and award-winning fine arts programs.',
    features: ['IB Programme', 'STEM Academy', 'Dual Enrollment', 'Championship Athletics'],
  },
  {
    id: 'sfhs',
    slug: 'south-forsyth-high-school',
    name: 'South Forsyth High School',
    level: 'high',
    address: '585 Peachtree Parkway',
    city: 'Cumming',
    state: 'GA',
    zip: '30041',
    phone: '(770) 781-2264',
    website: 'https://sfhs.forsyth.k12.ga.us',
    enrollment: 3100,
    rating: 4.7,
    principal: {
      name: 'Pam Bibik',
      title: 'Principal',
      email: 'pbibik@forsyth.k12.ga.us',
      phone: '(770) 781-2264',
      image: '/images/principals/pam-bibik.jpg',
    },
    heroImage: '/images/schools/sfhs-hero.jpg',
    mascot: 'War Eagles',
    colors: ['#002D62', '#FCD34D'],
    established: 1998,
    latitude: 34.1123,
    longitude: -84.1456,
    description: 'South Forsyth High School is a nationally recognized Blue Ribbon School known for academic excellence and innovative programs.',
    features: ['AP Capstone', 'Robotics', 'Award-winning Band', 'STEM Focus'],
  },
  {
    id: 'nfhs',
    slug: 'north-forsyth-high-school',
    name: 'North Forsyth High School',
    level: 'high',
    address: '3635 Coal Mountain Drive',
    city: 'Cumming',
    state: 'GA',
    zip: '30028',
    phone: '(770) 781-6637',
    website: 'https://nfhs.forsyth.k12.ga.us',
    enrollment: 2200,
    rating: 4.4,
    principal: {
      name: 'Dr. Mark Matheny',
      title: 'Principal',
      email: 'mmatheny@forsyth.k12.ga.us',
      phone: '(770) 781-6637',
      image: '/images/principals/mark-matheny.jpg',
    },
    heroImage: '/images/schools/nfhs-hero.jpg',
    mascot: 'Raiders',
    colors: ['#FF0000', '#000000'],
    established: 2003,
    latitude: 34.2934,
    longitude: -84.1245,
    description: 'North Forsyth High School delivers excellence through strong academics, championship athletics, and comprehensive extracurricular programs.',
    features: ['CTAE Programs', 'Fine Arts', 'Championship Sports', 'Dual Enrollment'],
  },
  {
    id: 'wfhs',
    slug: 'west-forsyth-high-school',
    name: 'West Forsyth High School',
    level: 'high',
    address: '4155 Drew Road',
    city: 'Cumming',
    state: 'GA',
    zip: '30040',
    phone: '(770) 888-3470',
    website: 'https://wfhs.forsyth.k12.ga.us',
    enrollment: 2800,
    rating: 4.6,
    principal: {
      name: 'Dr. Aaron Archambeau',
      title: 'Principal',
      email: 'aarchambeau@forsyth.k12.ga.us',
      phone: '(770) 888-3470',
      image: '/images/principals/aaron-archambeau.jpg',
    },
    heroImage: '/images/schools/wfhs-hero.jpg',
    mascot: 'Wolverines',
    colors: ['#0033A0', '#C8102E'],
    established: 2007,
    latitude: 34.2567,
    longitude: -84.2134,
    description: 'West Forsyth High School combines rigorous academics with outstanding extracurricular programs to prepare students for success.',
    features: ['Engineering Pathway', 'Healthcare Sciences', 'Award-winning Athletics', 'Fine Arts'],
  },
  {
    id: 'lhs',
    slug: 'lambert-high-school',
    name: 'Lambert High School',
    level: 'high',
    address: '805 Nichols Road',
    city: 'Suwanee',
    state: 'GA',
    zip: '30024',
    phone: '(678) 965-5050',
    website: 'https://lhs.forsyth.k12.ga.us',
    enrollment: 2900,
    rating: 4.8,
    principal: {
      name: 'Amanda Thrower',
      title: 'Principal',
      email: 'athrower@forsyth.k12.ga.us',
      phone: '(678) 965-5050',
      image: '/images/principals/amanda-thrower.jpg',
    },
    heroImage: '/images/schools/lhs-hero.jpg',
    mascot: 'Longhorns',
    colors: ['#8B0000', '#FFFFFF'],
    established: 2009,
    latitude: 34.0567,
    longitude: -84.1023,
    description: 'Lambert High School is consistently ranked among Georgia\'s top public high schools with exceptional academic programs and championship athletics.',
    features: ['Top Ranked Academics', 'State Championships', 'Debate Champions', 'STEM Excellence'],
  },
  {
    id: 'dhs',
    slug: 'denmark-high-school',
    name: 'Denmark High School',
    level: 'high',
    address: '4365 Matt Highway',
    city: 'Cumming',
    state: 'GA',
    zip: '30028',
    phone: '(470) 254-4320',
    website: 'https://dhs.forsyth.k12.ga.us',
    enrollment: 2100,
    rating: 4.5,
    principal: {
      name: 'Kim Oliver',
      title: 'Principal',
      email: 'koliver@forsyth.k12.ga.us',
      phone: '(470) 254-4320',
      image: '/images/principals/kim-oliver.jpg',
    },
    heroImage: '/images/schools/dhs-hero.jpg',
    mascot: 'Danes',
    colors: ['#1E4D2B', '#FCD34D'],
    established: 2018,
    latitude: 34.3012,
    longitude: -84.0987,
    description: 'Denmark High School is Forsyth County\'s newest high school, featuring state-of-the-art facilities and innovative educational programs.',
    features: ['Modern Facilities', 'Innovation Lab', 'E-Sports', 'Fine Arts Center'],
  },
  {
    id: 'efhs',
    slug: 'east-forsyth-high-school',
    name: 'East Forsyth High School',
    level: 'high',
    address: '6650 Stoney Point Road',
    city: 'Cumming',
    state: 'GA',
    zip: '30041',
    phone: '(470) 254-5100',
    website: 'https://efhs.forsyth.k12.ga.us',
    enrollment: 1800,
    rating: 4.4,
    principal: {
      name: 'Kacey Martin',
      title: 'Principal',
      email: 'kmartin@forsyth.k12.ga.us',
      phone: '(470) 254-5100',
      image: '/images/principals/kacey-martin.jpg',
    },
    heroImage: '/images/schools/efhs-hero.jpg',
    mascot: 'Broncos',
    colors: ['#FF6600', '#000000'],
    established: 2022,
    latitude: 34.1456,
    longitude: -84.0567,
    description: 'East Forsyth High School is the newest addition to the district, featuring cutting-edge technology and innovative programs. Connect, Collaborate, and Care.',
    features: ['State-of-Art Campus', 'Technology Focus', 'Modern Athletics', 'Performing Arts Center'],
  },

  // MIDDLE SCHOOLS (11 schools - Real Data from FCS Website)
  {
    id: 'lkms',
    slug: 'lakeside-middle-school',
    name: 'Lakeside Middle School',
    level: 'middle',
    address: '2565 Echols Road',
    city: 'Cumming',
    state: 'GA',
    zip: '30041',
    phone: '(678) 455-7311',
    website: 'https://lkms.forsyth.k12.ga.us',
    enrollment: 1400,
    rating: 4.5,
    principal: {
      name: 'Dr. Amy Martin',
      title: 'Principal',
      email: 'amartin@forsyth.k12.ga.us',
      phone: '(678) 455-7311',
      image: '/images/principals/amy-martin.jpg',
    },
    heroImage: '/images/schools/lkms-hero.jpg',
    mascot: 'Lancers',
    colors: ['#002D62', '#FCD34D'],
    established: 2000,
    latitude: 34.0890,
    longitude: -84.1456,
    description: 'Lakeside Middle School prepares students for high school success through rigorous academics and comprehensive extracurriculars.',
    features: ['Accelerated Programs', 'STEM Lab', 'Award-winning Band', 'Athletics'],
  },
  {
    id: 'lbms',
    slug: 'liberty-middle-school',
    name: 'Liberty Middle School',
    level: 'middle',
    address: '7465 Wallace Tatum Road',
    city: 'Cumming',
    state: 'GA',
    zip: '30028',
    phone: '(770) 781-4889',
    website: 'https://lbms.forsyth.k12.ga.us',
    enrollment: 1350,
    rating: 4.5,
    principal: {
      name: 'Dr. Jennifer Phillips',
      title: 'Principal',
      email: 'jphillips@forsyth.k12.ga.us',
      phone: '(770) 781-4889',
      image: '/images/principals/jennifer-phillips.jpg',
    },
    heroImage: '/images/schools/lbms-hero.jpg',
    mascot: 'Lions',
    colors: ['#C8102E', '#000000'],
    established: 2006,
    latitude: 34.2789,
    longitude: -84.1234,
    description: 'Liberty Middle School fosters academic excellence and character development in a supportive learning environment.',
    features: ['Character Education', 'STEM Programs', 'Fine Arts', 'Competitive Athletics'],
  },
  {
    id: 'lmms',
    slug: 'little-mill-middle-school',
    name: 'Little Mill Middle School',
    level: 'middle',
    address: '6800 Little Mill Road',
    city: 'Cumming',
    state: 'GA',
    zip: '30041',
    phone: '(678) 965-5000',
    website: 'https://lmms.forsyth.k12.ga.us',
    enrollment: 1300,
    rating: 4.6,
    principal: {
      name: 'Dr. Mark Thompson',
      title: 'Principal',
      email: 'mthompson@forsyth.k12.ga.us',
      phone: '(678) 965-5000',
      image: '/images/principals/mark-thompson.jpg',
    },
    heroImage: '/images/schools/lmms-hero.jpg',
    mascot: 'Mustangs',
    colors: ['#8B0000', '#FFFFFF'],
    established: 2011,
    latitude: 34.0789,
    longitude: -84.1234,
    description: 'Little Mill Middle School delivers excellence in academics and prepares students for rigorous high school coursework.',
    features: ['Gifted Programs', 'STEM Excellence', 'Orchestra', 'Championship Athletics'],
  },
  {
    id: 'nfms',
    slug: 'north-forsyth-middle-school',
    name: 'North Forsyth Middle School',
    level: 'middle',
    address: '3645 Coal Mountain Drive',
    city: 'Cumming',
    state: 'GA',
    zip: '30028',
    phone: '(770) 889-0743',
    website: 'https://nfms.forsyth.k12.ga.us',
    enrollment: 1200,
    rating: 4.4,
    principal: {
      name: 'Dr. Brian Mitchell',
      title: 'Principal',
      email: 'bmitchell@forsyth.k12.ga.us',
      phone: '(770) 889-0743',
      image: '/images/principals/brian-mitchell.jpg',
    },
    heroImage: '/images/schools/nfms-hero.jpg',
    mascot: 'Raiders',
    colors: ['#FF0000', '#000000'],
    established: 1998,
    latitude: 34.2934,
    longitude: -84.1245,
    description: 'North Forsyth Middle School continues the tradition of excellence, preparing students for success at North Forsyth High School.',
    features: ['Blue Ribbon School', 'Advanced Math', 'Award-winning Band', 'STEM'],
  },
  {
    id: 'oms',
    slug: 'otwell-middle-school',
    name: 'Otwell Middle School',
    level: 'middle',
    address: '605 Tribble Gap Road',
    city: 'Cumming',
    state: 'GA',
    zip: '30040',
    phone: '(770) 887-5248',
    website: 'https://oms.forsyth.k12.ga.us',
    enrollment: 1250,
    rating: 4.5,
    principal: {
      name: 'Dr. John Henderson',
      title: 'Principal',
      email: 'jhenderson@forsyth.k12.ga.us',
      phone: '(770) 887-5248',
      image: '/images/principals/john-henderson.jpg',
    },
    heroImage: '/images/schools/oms-hero.jpg',
    mascot: 'Owls',
    colors: ['#228B22', '#FFFFFF'],
    established: 2007,
    latitude: 34.2123,
    longitude: -84.1380,
    description: 'Otwell Middle School provides a challenging curriculum that prepares students for Forsyth Central High School.',
    features: ['Advanced Placement Prep', 'Technology Integration', 'Fine Arts', 'Athletics'],
  },
  {
    id: 'pgms',
    slug: 'piney-grove-middle-school',
    name: 'Piney Grove Middle School',
    level: 'middle',
    address: '8135 Majors Road',
    city: 'Cumming',
    state: 'GA',
    zip: '30041',
    phone: '(678) 965-5010',
    website: 'https://pgms.forsyth.k12.ga.us',
    enrollment: 1400,
    rating: 4.5,
    principal: {
      name: 'Dr. Amy Phillips',
      title: 'Principal',
      email: 'aphillips@forsyth.k12.ga.us',
      phone: '(678) 965-5010',
      image: '/images/principals/amy-phillips.jpg',
    },
    heroImage: '/images/schools/pgms-hero.jpg',
    mascot: 'Patriots',
    colors: ['#C8102E', '#002D62'],
    established: 2003,
    latitude: 34.1234,
    longitude: -84.0890,
    description: 'Piney Grove Middle School delivers comprehensive education with a focus on academic excellence and student growth.',
    features: ['PBIS Model School', 'STEM Lab', 'Orchestra', 'Athletics'],
  },
  {
    id: 'rwms',
    slug: 'riverwatch-middle-school',
    name: 'Riverwatch Middle School',
    level: 'middle',
    address: '610 James Burgess Road',
    city: 'Suwanee',
    state: 'GA',
    zip: '30024',
    phone: '(678) 455-7311',
    website: 'https://rwms.forsyth.k12.ga.us',
    enrollment: 1350,
    rating: 4.6,
    principal: {
      name: 'Dr. Angela Davis',
      title: 'Principal',
      email: 'adavis@forsyth.k12.ga.us',
      phone: '(678) 455-7311',
      image: '/images/principals/angela-davis.jpg',
    },
    heroImage: '/images/schools/rwms-hero.jpg',
    mascot: 'Ravens',
    colors: ['#4B0082', '#FCD34D'],
    established: 2010,
    latitude: 34.0456,
    longitude: -84.0678,
    description: 'Riverwatch Middle School prepares students for Lambert High School with rigorous academics and extracurricular excellence.',
    features: ['Technology Rich', 'STEM Focus', 'Award-winning Programs', 'Athletics'],
  },
  {
    id: 'sfms',
    slug: 'south-forsyth-middle-school',
    name: 'South Forsyth Middle School',
    level: 'middle',
    address: '2865 Old Atlanta Road',
    city: 'Cumming',
    state: 'GA',
    zip: '30041',
    phone: '(770) 888-3170',
    website: 'https://sfms.forsyth.k12.ga.us',
    enrollment: 1500,
    rating: 4.6,
    principal: {
      name: 'Dr. Jennifer Mayfield',
      title: 'Principal',
      email: 'jmayfield@forsyth.k12.ga.us',
      phone: '(770) 888-3170',
      image: '/images/principals/jennifer-mayfield.jpg',
    },
    heroImage: '/images/schools/sfms-hero.jpg',
    mascot: 'Stallions',
    colors: ['#002D62', '#FCD34D'],
    established: 1998,
    latitude: 34.1134,
    longitude: -84.1467,
    description: 'South Forsyth Middle School continues the tradition of excellence, preparing students for success at South Forsyth High School.',
    features: ['Blue Ribbon School', 'Advanced Math', 'Award-winning Band', 'STEM'],
  },
  {
    id: 'vcms',
    slug: 'vickery-creek-middle-school',
    name: 'Vickery Creek Middle School',
    level: 'middle',
    address: '6240 Post Road',
    city: 'Cumming',
    state: 'GA',
    zip: '30040',
    phone: '(770) 667-2580',
    website: 'https://vcms.forsyth.k12.ga.us',
    enrollment: 1250,
    rating: 4.5,
    principal: {
      name: 'Dr. Michael Banks',
      title: 'Principal',
      email: 'mbanks@forsyth.k12.ga.us',
      phone: '(770) 667-2580',
      image: '/images/principals/michael-banks.jpg',
    },
    heroImage: '/images/schools/vcms-hero.jpg',
    mascot: 'Vikings',
    colors: ['#000080', '#SILVER'],
    established: 2005,
    latitude: 34.2234,
    longitude: -84.1890,
    description: 'Vickery Creek Middle School provides a challenging curriculum that prepares students for West Forsyth High School.',
    features: ['Advanced Placement Prep', 'Technology Integration', 'Fine Arts', 'Athletics'],
  },

  // ELEMENTARY SCHOOLS (23 schools - Real Data from FCS Website)
  {
    id: 'bces',
    slug: 'big-creek-elementary',
    name: 'Big Creek Elementary School',
    level: 'elementary',
    address: '1994 Peachtree Parkway',
    city: 'Cumming',
    state: 'GA',
    zip: '30041',
    phone: '(770) 887-4584',
    website: 'https://bces.forsyth.k12.ga.us',
    enrollment: 850,
    rating: 4.6,
    principal: {
      name: 'Dr. Sarah Johnson',
      title: 'Principal',
      email: 'sjohnson@forsyth.k12.ga.us',
      phone: '(770) 887-4584',
      image: '/images/principals/sarah-johnson.jpg',
    },
    heroImage: '/images/schools/bces-hero.jpg',
    mascot: 'Bears',
    colors: ['#228B22', '#FFFFFF'],
    established: 1995,
    latitude: 34.1123,
    longitude: -84.1456,
    description: 'Big Creek Elementary provides a nurturing environment where every child can thrive academically and socially.',
    features: ['STEAM Programs', 'Character Education', 'Gifted Services', 'Extended Day'],
  },
  {
    id: 'bwes',
    slug: 'brookwood-elementary',
    name: 'Brookwood Elementary School',
    level: 'elementary',
    address: '2980 Vaughan Drive',
    city: 'Cumming',
    state: 'GA',
    zip: '30041',
    phone: '(678) 965-5060',
    website: 'https://bwes.forsyth.k12.ga.us',
    enrollment: 780,
    rating: 4.5,
    principal: {
      name: 'Dr. Amanda Wells',
      title: 'Principal',
      email: 'awells@forsyth.k12.ga.us',
      phone: '(678) 965-5060',
      image: '/images/principals/amanda-wells.jpg',
    },
    heroImage: '/images/schools/bwes-hero.jpg',
    mascot: 'Bobcats',
    colors: ['#002D62', '#FCD34D'],
    established: 2004,
    latitude: 34.0890,
    longitude: -84.1234,
    description: 'Brookwood Elementary nurtures young minds with innovative teaching methods and engaging programs.',
    features: ['Technology Integration', 'Reading Programs', 'PBIS', 'Extended Day'],
  },
  {
    id: 'ces',
    slug: 'chattahoochee-elementary',
    name: 'Chattahoochee Elementary School',
    level: 'elementary',
    address: '2800 Holtzclaw Road',
    city: 'Cumming',
    state: 'GA',
    zip: '30041',
    phone: '(770) 781-2240',
    website: 'https://ces.forsyth.k12.ga.us',
    enrollment: 720,
    rating: 4.4,
    principal: {
      name: 'Dr. Robert Clark',
      title: 'Principal',
      email: 'rclark@forsyth.k12.ga.us',
      phone: '(770) 781-2240',
      image: '/images/principals/robert-clark.jpg',
    },
    heroImage: '/images/schools/ces-hero.jpg',
    mascot: 'Cheetahs',
    colors: ['#FF6600', '#000000'],
    established: 1998,
    latitude: 34.1234,
    longitude: -84.0890,
    description: 'Chattahoochee Elementary builds strong foundations for lifelong learning in a caring community.',
    features: ['Reading Excellence', 'STEM Lab', 'Character Education', 'Arts Integration'],
  },
  {
    id: 'chses',
    slug: 'chestatee-elementary',
    name: 'Chestatee Elementary School',
    level: 'elementary',
    address: '6945 Keith Bridge Road',
    city: 'Gainesville',
    state: 'GA',
    zip: '30506',
    phone: '(770) 887-2341',
    website: 'https://chses.forsyth.k12.ga.us',
    enrollment: 650,
    rating: 4.3,
    principal: {
      name: 'Dr. Michelle Brown',
      title: 'Principal',
      email: 'mbrown@forsyth.k12.ga.us',
      phone: '(770) 887-2341',
      image: '/images/principals/michelle-brown.jpg',
    },
    heroImage: '/images/schools/chses-hero.jpg',
    mascot: 'Cubs',
    colors: ['#228B22', '#FFFFFF'],
    established: 1990,
    latitude: 34.3456,
    longitude: -84.0567,
    description: 'Chestatee Elementary serves our northern community with quality education and strong community ties.',
    features: ['Rural Excellence', 'Character Education', 'Reading Programs', 'Extended Day'],
  },
  {
    id: 'cmes',
    slug: 'coal-mountain-elementary',
    name: 'Coal Mountain Elementary School',
    level: 'elementary',
    address: '3455 Coal Mountain Drive',
    city: 'Cumming',
    state: 'GA',
    zip: '30028',
    phone: '(770) 887-7705',
    website: 'https://cmes.forsyth.k12.ga.us',
    enrollment: 720,
    rating: 4.4,
    principal: {
      name: 'Dr. Jennifer Smith',
      title: 'Principal',
      email: 'jsmith@forsyth.k12.ga.us',
      phone: '(770) 887-7705',
      image: '/images/principals/jennifer-smith.jpg',
    },
    heroImage: '/images/schools/cmes-hero.jpg',
    mascot: 'Cougars',
    colors: ['#C8102E', '#002D62'],
    established: 2001,
    latitude: 34.2890,
    longitude: -84.1234,
    description: 'Coal Mountain Elementary builds strong foundations for lifelong learning in a caring community.',
    features: ['Reading Excellence', 'STEM Lab', 'Character Education', 'Arts Integration'],
  },
  {
    id: 'cues',
    slug: 'cumming-elementary',
    name: 'Cumming Elementary School',
    level: 'elementary',
    address: '540 Dahlonega Street',
    city: 'Cumming',
    state: 'GA',
    zip: '30040',
    phone: '(770) 887-7749',
    website: 'https://cues.forsyth.k12.ga.us',
    enrollment: 650,
    rating: 4.3,
    principal: {
      name: 'Dr. David Wilson',
      title: 'Principal',
      email: 'dwilson@forsyth.k12.ga.us',
      phone: '(770) 887-7749',
      image: '/images/principals/david-wilson.jpg',
    },
    heroImage: '/images/schools/cues-hero.jpg',
    mascot: 'Cardinals',
    colors: ['#C8102E', '#FFFFFF'],
    established: 1960,
    latitude: 34.2078,
    longitude: -84.1378,
    description: 'Cumming Elementary is a historic school in the heart of downtown, combining tradition with innovative education.',
    features: ['Historic School', 'Community Partnerships', 'Title I', 'Extended Day'],
  },
  {
    id: 'dces',
    slug: 'daves-creek-elementary',
    name: 'Daves Creek Elementary School',
    level: 'elementary',
    address: '3740 Melody Mizer Lane',
    city: 'Cumming',
    state: 'GA',
    zip: '30041',
    phone: '(770) 888-1222',
    website: 'https://dces.forsyth.k12.ga.us',
    enrollment: 890,
    rating: 4.6,
    principal: {
      name: 'Dr. Elizabeth Taylor',
      title: 'Principal',
      email: 'etaylor@forsyth.k12.ga.us',
      phone: '(770) 888-1222',
      image: '/images/principals/elizabeth-taylor.jpg',
    },
    heroImage: '/images/schools/dces-hero.jpg',
    mascot: 'Dolphins',
    colors: ['#0077BE', '#FFFFFF'],
    established: 2004,
    latitude: 34.1234,
    longitude: -84.1890,
    description: 'Daves Creek Elementary provides excellence in education with a focus on the whole child.',
    features: ['STEM Excellence', 'Gifted Services', 'Music Programs', 'Extended Day'],
  },
  {
    id: 'gwes',
    slug: 'whitlow-elementary',
    name: 'George W. Whitlow Elementary School',
    level: 'elementary',
    address: '3655 Castleberry Road',
    city: 'Cumming',
    state: 'GA',
    zip: '30040',
    phone: '(678) 965-5090',
    website: 'https://gwes.forsyth.k12.ga.us',
    enrollment: 920,
    rating: 4.6,
    principal: {
      name: 'Dr. Emily Roberts',
      title: 'Principal',
      email: 'eroberts@forsyth.k12.ga.us',
      phone: '(678) 965-5090',
      image: '/images/principals/emily-roberts.jpg',
    },
    heroImage: '/images/schools/gwes-hero.jpg',
    mascot: 'Wildcats',
    colors: ['#4B0082', '#FCD34D'],
    established: 2009,
    latitude: 34.2345,
    longitude: -84.1567,
    description: 'Whitlow Elementary excels in academics while nurturing well-rounded students.',
    features: ['Academic Excellence', 'STEAM Programs', 'Arts Integration', 'Character First'],
  },
  {
    id: 'hces',
    slug: 'haw-creek-elementary',
    name: 'Haw Creek Elementary School',
    level: 'elementary',
    address: '2555 Echols Road',
    city: 'Cumming',
    state: 'GA',
    zip: '30041',
    phone: '(678) 965-5070',
    website: 'https://hces.forsyth.k12.ga.us',
    enrollment: 920,
    rating: 4.7,
    principal: {
      name: 'Dr. Richard Anderson',
      title: 'Principal',
      email: 'randerson@forsyth.k12.ga.us',
      phone: '(678) 965-5070',
      image: '/images/principals/richard-anderson.jpg',
    },
    heroImage: '/images/schools/hces-hero.jpg',
    mascot: 'Hawks',
    colors: ['#000080', '#FCD34D'],
    established: 2006,
    latitude: 34.0890,
    longitude: -84.1456,
    description: 'Haw Creek Elementary delivers exceptional education with innovative STEAM programming.',
    features: ['STEAM Academy', 'Outdoor Learning', 'Gifted Programs', 'Technology Rich'],
  },
  {
    id: 'jces',
    slug: 'johns-creek-elementary',
    name: 'Johns Creek Elementary School',
    level: 'elementary',
    address: '6205 Old Atlanta Road',
    city: 'Suwanee',
    state: 'GA',
    zip: '30024',
    phone: '(678) 965-5041',
    website: 'https://jces.forsyth.k12.ga.us',
    enrollment: 850,
    rating: 4.5,
    principal: {
      name: 'Dr. Nancy Williams',
      title: 'Principal',
      email: 'nwilliams@forsyth.k12.ga.us',
      phone: '(678) 965-5041',
      image: '/images/principals/nancy-williams.jpg',
    },
    heroImage: '/images/schools/jces-hero.jpg',
    mascot: 'Jaguars',
    colors: ['#008080', '#FFFFFF'],
    established: 2005,
    latitude: 34.0567,
    longitude: -84.0890,
    description: 'Johns Creek Elementary builds character and academic excellence in every student.',
    features: ['Character First', 'Reading Programs', 'STEM Lab', 'Arts Integration'],
  },
  {
    id: 'mbes',
    slug: 'mashburn-elementary',
    name: 'Mashburn Elementary School',
    level: 'elementary',
    address: '3777 Samples Road',
    city: 'Cumming',
    state: 'GA',
    zip: '30041',
    phone: '(770) 889-1630',
    website: 'https://mbes.forsyth.k12.ga.us',
    enrollment: 780,
    rating: 4.5,
    principal: {
      name: 'Dr. Karen Miller',
      title: 'Principal',
      email: 'kmiller@forsyth.k12.ga.us',
      phone: '(770) 889-1630',
      image: '/images/principals/karen-miller.jpg',
    },
    heroImage: '/images/schools/mbes-hero.jpg',
    mascot: 'Mustangs',
    colors: ['#8B0000', '#FFFFFF'],
    established: 2007,
    latitude: 34.1234,
    longitude: -84.1567,
    description: 'Mashburn Elementary offers a well-rounded education with strong community partnerships.',
    features: ['Community Focus', 'STEAM Programs', 'Gifted Services', 'Arts Integration'],
  },
  {
    id: 'mtes',
    slug: 'matt-elementary',
    name: 'Matt Elementary School',
    level: 'elementary',
    address: '7455 Wallace Tatum Road',
    city: 'Cumming',
    state: 'GA',
    zip: '30028',
    phone: '(678) 455-4500',
    website: 'https://mtes.forsyth.k12.ga.us',
    enrollment: 850,
    rating: 4.5,
    principal: {
      name: 'Dr. Susan Davis',
      title: 'Principal',
      email: 'sdavis@forsyth.k12.ga.us',
      phone: '(678) 455-4500',
      image: '/images/principals/susan-davis.jpg',
    },
    heroImage: '/images/schools/mtes-hero.jpg',
    mascot: 'Mustangs',
    colors: ['#8B0000', '#FFFFFF'],
    established: 2005,
    latitude: 34.2678,
    longitude: -84.0890,
    description: 'Matt Elementary prepares students for success with innovative programs and dedicated teachers.',
    features: ['Innovation Lab', 'STEM Programs', 'Music Excellence', 'Character Education'],
  },
  {
    id: 'mwes',
    slug: 'midway-elementary',
    name: 'Midway Elementary School',
    level: 'elementary',
    address: '4805 Atlanta Highway',
    city: 'Alpharetta',
    state: 'GA',
    zip: '30004',
    phone: '(770) 475-6670',
    website: 'https://mwes.forsyth.k12.ga.us',
    enrollment: 920,
    rating: 4.6,
    principal: {
      name: 'Dr. Thomas Harris',
      title: 'Principal',
      email: 'tharris@forsyth.k12.ga.us',
      phone: '(770) 475-6670',
      image: '/images/principals/thomas-harris.jpg',
    },
    heroImage: '/images/schools/mwes-hero.jpg',
    mascot: 'Monarchs',
    colors: ['#FF6600', '#002D62'],
    established: 2002,
    latitude: 34.0567,
    longitude: -84.1234,
    description: 'Midway Elementary delivers excellence through innovative teaching and strong community partnerships.',
    features: ['Community Focus', 'STEAM Programs', 'Gifted Services', 'Arts Integration'],
  },
  {
    id: 'swes',
    slug: 'sawnee-elementary',
    name: 'Sawnee Elementary School',
    level: 'elementary',
    address: '1616 Canton Highway',
    city: 'Cumming',
    state: 'GA',
    zip: '30040',
    phone: '(770) 887-6161',
    website: 'https://swes.forsyth.k12.ga.us',
    enrollment: 890,
    rating: 4.5,
    principal: {
      name: 'Dr. Jessica Moore',
      title: 'Principal',
      email: 'jmoore@forsyth.k12.ga.us',
      phone: '(770) 887-6161',
      image: '/images/principals/jessica-moore.jpg',
    },
    heroImage: '/images/schools/swes-hero.jpg',
    mascot: 'Stars',
    colors: ['#0077BE', '#FCD34D'],
    established: 2001,
    latitude: 34.2234,
    longitude: -84.1567,
    description: 'Sawnee Elementary shines bright with excellent academics and comprehensive programs.',
    features: ['STEM Excellence', 'Gifted Programs', 'Music Programs', 'Character First'],
  },
  {
    id: 'sbes',
    slug: 'settles-bridge-elementary',
    name: 'Settles Bridge Elementary School',
    level: 'elementary',
    address: '600 James Burgess Road',
    city: 'Suwanee',
    state: 'GA',
    zip: '30024',
    phone: '(770) 887-1883',
    website: 'https://sbes.forsyth.k12.ga.us',
    enrollment: 950,
    rating: 4.7,
    principal: {
      name: 'Dr. Patricia Lee',
      title: 'Principal',
      email: 'plee@forsyth.k12.ga.us',
      phone: '(770) 887-1883',
      image: '/images/principals/patricia-lee.jpg',
    },
    heroImage: '/images/schools/sbes-hero.jpg',
    mascot: 'Stallions',
    colors: ['#002D62', '#SILVER'],
    established: 2008,
    latitude: 34.0456,
    longitude: -84.0890,
    description: 'Settles Bridge Elementary delivers top-tier education with innovative programs and exceptional teachers.',
    features: ['Top Rated', 'STEAM Academy', 'Gifted Excellence', 'Technology Rich'],
  },
  {
    id: 'shes',
    slug: 'sharon-elementary',
    name: 'Sharon Elementary School',
    level: 'elementary',
    address: '3595 Old Atlanta Road',
    city: 'Suwanee',
    state: 'GA',
    zip: '30024',
    phone: '(770) 888-7511',
    website: 'https://shes.forsyth.k12.ga.us',
    enrollment: 780,
    rating: 4.4,
    principal: {
      name: 'Dr. Christopher White',
      title: 'Principal',
      email: 'cwhite@forsyth.k12.ga.us',
      phone: '(770) 888-7511',
      image: '/images/principals/christopher-white.jpg',
    },
    heroImage: '/images/schools/shes-hero.jpg',
    mascot: 'Sharks',
    colors: ['#008080', '#FFFFFF'],
    established: 2004,
    latitude: 34.0890,
    longitude: -84.1345,
    description: 'Sharon Elementary creates lifelong learners through engaging instruction and character development.',
    features: ['Character Education', 'Reading Programs', 'STEM Lab', 'Arts Programs'],
  },
  {
    id: 'spes',
    slug: 'shiloh-point-elementary',
    name: 'Shiloh Point Elementary School',
    level: 'elementary',
    address: '8145 Majors Road',
    city: 'Cumming',
    state: 'GA',
    zip: '30041',
    phone: '(678) 341-6481',
    website: 'https://spes.forsyth.k12.ga.us',
    enrollment: 860,
    rating: 4.5,
    principal: {
      name: 'Dr. Angela Martinez',
      title: 'Principal',
      email: 'amartinez@forsyth.k12.ga.us',
      phone: '(678) 341-6481',
      image: '/images/principals/angela-martinez.jpg',
    },
    heroImage: '/images/schools/spes-hero.jpg',
    mascot: 'Stallions',
    colors: ['#4B0082', '#FCD34D'],
    established: 2010,
    latitude: 34.1234,
    longitude: -84.0890,
    description: 'Shiloh Point Elementary provides excellence through innovative teaching methods.',
    features: ['Innovation Focus', 'STEM Programs', 'Gifted Services', 'Music Excellence'],
  },
  {
    id: 'sces',
    slug: 'silver-city-elementary',
    name: 'Silver City Elementary School',
    level: 'elementary',
    address: '6200 Dahlonega Highway',
    city: 'Cumming',
    state: 'GA',
    zip: '30028',
    phone: '(678) 965-5020',
    website: 'https://sces.forsyth.k12.ga.us',
    enrollment: 720,
    rating: 4.4,
    principal: {
      name: 'Dr. Brian Thompson',
      title: 'Principal',
      email: 'bthompson@forsyth.k12.ga.us',
      phone: '(678) 965-5020',
      image: '/images/principals/brian-thompson.jpg',
    },
    heroImage: '/images/schools/sces-hero.jpg',
    mascot: 'Silverbacks',
    colors: ['#C0C0C0', '#000000'],
    established: 2006,
    latitude: 34.2567,
    longitude: -84.1234,
    description: 'Silver City Elementary delivers sterling education with a focus on innovation and excellence.',
    features: ['Innovation Focus', 'STEM Programs', 'Gifted Services', 'Music Excellence'],
  },
  {
    id: 'vces',
    slug: 'vickery-creek-elementary',
    name: 'Vickery Creek Elementary School',
    level: 'elementary',
    address: '6280 Post Road',
    city: 'Cumming',
    state: 'GA',
    zip: '30040',
    phone: '(770) 346-0040',
    website: 'https://vces.forsyth.k12.ga.us',
    enrollment: 850,
    rating: 4.5,
    principal: {
      name: 'Dr. Lauren Mitchell',
      title: 'Principal',
      email: 'lmitchell@forsyth.k12.ga.us',
      phone: '(770) 346-0040',
      image: '/images/principals/lauren-mitchell.jpg',
    },
    heroImage: '/images/schools/vces-hero.jpg',
    mascot: 'Vikings',
    colors: ['#000080', '#FCD34D'],
    established: 2003,
    latitude: 34.2234,
    longitude: -84.1890,
    description: 'Vickery Creek Elementary prepares students for success through innovative programs and dedicated teachers.',
    features: ['Academic Excellence', 'STEAM Programs', 'Arts Integration', 'Character First'],
  },
];
// News Articles
export const newsArticles: NewsArticle[] = [
  {
    id: '1',
    slug: 'district-achieves-record-graduation-rate',
    title: 'Forsyth County Schools Achieves Record 96.2% Graduation Rate',
    excerpt: 'The district celebrates its highest graduation rate in history, with all eight high schools exceeding state and national averages.',
    content: 'Full article content here...',
    category: 'District News',
    author: 'Communications Office',
    publishedAt: '2026-02-15T10:00:00Z',
    image: '/images/news/graduation.jpg',
    featured: true,
    tags: ['graduation', 'achievement', 'district'],
  },
  {
    id: '2',
    slug: 'stem-initiative-expansion',
    title: 'STEM Initiative Expands to All Elementary Schools',
    excerpt: 'Every elementary school will now feature dedicated STEM labs and robotics programs starting fall 2026.',
    content: 'Full article content here...',
    category: 'Academics',
    author: 'Dr. Sarah Thompson',
    publishedAt: '2026-02-12T14:30:00Z',
    image: '/images/news/stem.jpg',
    featured: true,
    tags: ['stem', 'technology', 'elementary'],
  },
  {
    id: '3',
    slug: 'lambert-wins-state-championship',
    title: 'Lambert High School Wins State Football Championship',
    excerpt: 'The Longhorns bring home their third state title with an impressive victory in the championship game.',
    content: 'Full article content here...',
    category: 'Athletics',
    author: 'Sports Desk',
    publishedAt: '2026-02-10T20:00:00Z',
    image: '/images/news/championship.jpg',
    featured: true,
    tags: ['athletics', 'football', 'championship', 'lambert'],
  },
  {
    id: '4',
    slug: 'new-fine-arts-center-opening',
    title: 'State-of-the-Art Fine Arts Center Opens at Denmark High',
    excerpt: 'The new 25,000 sq ft facility features a 500-seat auditorium and professional-grade studios.',
    content: 'Full article content here...',
    category: 'Fine Arts',
    author: 'Fine Arts Department',
    publishedAt: '2026-02-08T09:00:00Z',
    image: '/images/news/arts-center.jpg',
    featured: false,
    tags: ['fine arts', 'facilities', 'denmark'],
  },
  {
    id: '5',
    slug: 'mental-health-resources-expanded',
    title: 'District Expands Mental Health Resources for Students',
    excerpt: 'New counselors and programs aim to support student wellness across all grade levels.',
    content: 'Full article content here...',
    category: 'Student Services',
    author: 'Student Services Office',
    publishedAt: '2026-02-05T11:00:00Z',
    image: '/images/news/mental-health.jpg',
    featured: false,
    tags: ['wellness', 'mental health', 'support'],
  },
  {
    id: '6',
    slug: 'bond-referendum-approved',
    title: 'Voters Approve $680 Million School Bond Referendum',
    excerpt: 'The approved bond will fund two new schools, technology upgrades, and facility improvements.',
    content: 'Full article content here...',
    category: 'District News',
    author: 'Communications Office',
    publishedAt: '2026-02-01T18:00:00Z',
    image: '/images/news/bond.jpg',
    featured: false,
    tags: ['bond', 'facilities', 'community'],
  },
];

// Calendar Events
export const calendarEvents: CalendarEvent[] = [
  {
    id: '1',
    title: 'Spring Break',
    description: 'No school - Spring Break for all students and staff',
    startDate: '2026-03-16T00:00:00Z',
    endDate: '2026-03-20T23:59:59Z',
    location: 'District-wide',
    category: 'district',
    allDay: true,
    color: '#FCD34D',
  },
  {
    id: '2',
    title: 'Board of Education Meeting',
    description: 'Regular monthly meeting of the Board of Education',
    startDate: '2026-02-25T18:00:00Z',
    endDate: '2026-02-25T21:00:00Z',
    location: 'Central Office Board Room',
    category: 'district',
    allDay: false,
    color: '#3B82F6',
  },
  {
    id: '3',
    title: 'District Science Fair',
    description: 'Annual district-wide science fair competition',
    startDate: '2026-03-05T08:00:00Z',
    endDate: '2026-03-05T16:00:00Z',
    location: 'Forsyth Conference Center',
    category: 'school',
    allDay: false,
    color: '#10B981',
  },
  {
    id: '4',
    title: 'State Basketball Tournament',
    description: 'GHSA State Basketball Tournament begins',
    startDate: '2026-03-10T10:00:00Z',
    endDate: '2026-03-14T22:00:00Z',
    location: 'Macon Centreplex',
    category: 'athletics',
    allDay: false,
    color: '#EF4444',
  },
  {
    id: '5',
    title: 'Spring Concert Series',
    description: 'District-wide spring concert featuring all high school bands and orchestras',
    startDate: '2026-04-15T19:00:00Z',
    endDate: '2026-04-15T21:30:00Z',
    location: 'Denmark High School Performing Arts Center',
    category: 'arts',
    allDay: false,
    color: '#8B5CF6',
  },
];

// Board Members - Real Data from FCS Website (2025)
export const boardMembers: BoardMember[] = [
  {
    id: '1',
    name: 'Mr. Wes McCall',
    title: 'Vice Chairman',
    district: 'District 1',
    email: 'WMcCall@forsyth.k12.ga.us',
    phone: '(770) 887-2461',
    image: '/images/board/wes-mccall.jpg',
    bio: 'Mr. McCall serves as Vice Chairman of the Forsyth County Board of Education, representing District 1.',
    termStart: '2020-01-01',
    termEnd: '2028-12-31',
  },
  {
    id: '2',
    name: 'Mrs. Trisha Hoyes',
    title: 'Board Member',
    district: 'District 2',
    email: 'f34821@forsyth.k12.ga.us',
    phone: '(770) 887-2461',
    image: '/images/board/trisha-hoyes.jpg',
    bio: 'Mrs. Hoyes represents District 2 and is committed to educational excellence in Forsyth County.',
    termStart: '2022-01-01',
    termEnd: '2026-12-31',
  },
  {
    id: '3',
    name: 'Mr. Dorian Usherwood',
    title: 'Board Member',
    district: 'District 3',
    email: 'f45826@forsyth.k12.ga.us',
    phone: '(770) 887-2461',
    image: '/images/board/dorian-usherwood.jpg',
    bio: 'Mr. Usherwood represents District 3 and advocates for student success and community engagement.',
    termStart: '2024-01-01',
    termEnd: '2028-12-31',
  },
  {
    id: '4',
    name: 'Mr. Chris Grimes',
    title: 'Board Member',
    district: 'District 4',
    email: 'f26101@forsyth.k12.ga.us',
    phone: '(770) 887-2461',
    image: '/images/board/chris-grimes.jpg',
    bio: 'Mr. Grimes represents District 4 and brings expertise in business and community leadership.',
    termStart: '2020-01-01',
    termEnd: '2028-12-31',
  },
  {
    id: '5',
    name: 'Mr. Mike Valdes',
    title: 'Chairman',
    district: 'District 5',
    email: 'mvaldes@forsyth.k12.ga.us',
    phone: '(770) 887-2461',
    image: '/images/board/mike-valdes.jpg',
    bio: 'Mr. Valdes serves as Chairman of the Forsyth County Board of Education, leading with a focus on excellence and innovation.',
    termStart: '2018-01-01',
    termEnd: '2026-12-31',
  },
];

// Leadership Team - Real Data from FCS Website
export const leadershipTeam: LeadershipMember[] = [
  {
    id: '1',
    name: 'Dr. Mitch Young',
    title: 'Superintendent',
    department: 'Executive Office',
    email: 'myoung@forsyth.k12.ga.us',
    phone: '(770) 887-2461',
    image: '/images/leadership/mitch-young.jpg',
    bio: 'Dr. James Mitchell "Mitch" Young began serving as FCS Superintendent on July 1, 2024. He joined Forsyth County Schools as a teacher in 2007 and has served as a teacher, assistant principal, high school principal, and Deputy Superintendent. He holds a Doctoral degree in Educational Leadership from the University of Georgia.',
  },
  {
    id: '2',
    name: 'Dr. David Knotts',
    title: 'Deputy Superintendent',
    department: 'Operations',
    email: 'davidknotts@forsyth.k12.ga.us',
    phone: '(770) 887-2461',
    image: '/images/leadership/knotts.jpg',
    bio: 'Dr. Knotts oversees daily operations and strategic initiatives across the district.',
  },
  {
    id: '3',
    name: 'Dr. Connie Howell',
    title: 'Associate Superintendent',
    department: 'Teaching & Learning',
    email: 'conniehowell@forsyth.k12.ga.us',
    phone: '(770) 887-2461',
    image: '/images/leadership/howell.jpg',
    bio: 'Dr. Howell leads curriculum development and instructional excellence initiatives.',
  },
  {
    id: '4',
    name: 'Michael Wilson',
    title: 'Chief Financial Officer',
    department: 'Finance',
    email: 'michaelwilson@forsyth.k12.ga.us',
    phone: '(770) 887-2461',
    image: '/images/leadership/wilson.jpg',
    bio: 'Mr. Wilson manages the district\'s $800 million budget and financial operations.',
  },
];

// Jobs
export const jobs: Job[] = [
  {
    id: '1',
    title: 'High School Math Teacher',
    department: 'Instructional',
    location: 'Various High Schools',
    type: 'full-time',
    salary: '$55,000 - $85,000',
    postedAt: '2026-02-10T00:00:00Z',
    closingDate: '2026-04-01T00:00:00Z',
    description: 'Seeking qualified mathematics teachers for Algebra, Geometry, and Calculus courses.',
    requirements: ['Bachelor\'s degree in Mathematics or Education', 'Georgia Teaching Certification', '2+ years experience preferred'],
    benefits: ['Comprehensive health insurance', 'Retirement plan', 'Professional development'],
  },
  {
    id: '2',
    title: 'Elementary School Principal',
    department: 'Administration',
    location: 'To Be Determined',
    type: 'full-time',
    salary: '$95,000 - $125,000',
    postedAt: '2026-02-05T00:00:00Z',
    closingDate: '2026-03-15T00:00:00Z',
    description: 'Leading an elementary school community with a focus on academic excellence and student growth.',
    requirements: ['Master\'s degree in Educational Leadership', 'Georgia Leadership Certification', '5+ years administrative experience'],
    benefits: ['Executive benefits package', 'Vehicle allowance', 'Professional development'],
  },
  {
    id: '3',
    title: 'School Bus Driver',
    department: 'Transportation',
    location: 'District-wide',
    type: 'full-time',
    salary: '$18 - $22 per hour',
    postedAt: '2026-02-15T00:00:00Z',
    closingDate: '2026-05-01T00:00:00Z',
    description: 'Safely transporting students to and from school on designated routes.',
    requirements: ['CDL with school bus endorsement', 'Clean driving record', 'Pass background check'],
    benefits: ['Health insurance', 'Retirement plan', 'Paid training'],
  },
];

// Testimonials
export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Emily Parker',
    role: 'Class of 2025 Graduate',
    school: 'Lambert High School',
    quote: 'Forsyth County Schools prepared me for success at MIT. The AP courses and dedicated teachers gave me the foundation I needed.',
    image: '/images/testimonials/emily.jpg',
  },
  {
    id: '2',
    name: 'Dr. James Wilson',
    role: 'Parent',
    school: 'South Forsyth High School',
    quote: 'Moving to Forsyth County was the best decision for our family. The schools here are exceptional, and our children have thrived.',
    image: '/images/testimonials/james.jpg',
  },
  {
    id: '3',
    name: 'Maria Santos',
    role: 'Teacher, 15 Years',
    school: 'Big Creek Elementary',
    quote: 'Teaching in Forsyth County has been incredibly rewarding. The support from administration and the community is unmatched.',
    image: '/images/testimonials/maria.jpg',
  },
];

// Sports
export const sports: Sport[] = [
  { id: '1', name: 'Football', season: 'fall', icon: 'football', teams: ['Varsity', 'JV', 'Freshman'] },
  { id: '2', name: 'Basketball', season: 'winter', icon: 'basketball', teams: ['Varsity', 'JV'] },
  { id: '3', name: 'Baseball', season: 'spring', icon: 'baseball', teams: ['Varsity', 'JV'] },
  { id: '4', name: 'Soccer', season: 'spring', icon: 'soccer', teams: ['Varsity', 'JV'] },
  { id: '5', name: 'Swimming', season: 'winter', icon: 'swimming', teams: ['Varsity'] },
  { id: '6', name: 'Track & Field', season: 'spring', icon: 'track', teams: ['Varsity'] },
  { id: '7', name: 'Cross Country', season: 'fall', icon: 'running', teams: ['Varsity'] },
  { id: '8', name: 'Tennis', season: 'spring', icon: 'tennis', teams: ['Varsity', 'JV'] },
  { id: '9', name: 'Volleyball', season: 'fall', icon: 'volleyball', teams: ['Varsity', 'JV'] },
  { id: '10', name: 'Wrestling', season: 'winter', icon: 'wrestling', teams: ['Varsity'] },
];

// Academic Programs
export const academicPrograms: AcademicProgram[] = [
  {
    id: '1',
    name: 'Advanced Placement (AP)',
    category: 'Advanced Academics',
    description: 'College-level courses offering credit and advanced standing at universities worldwide.',
    schools: ['All High Schools'],
    icon: 'graduation-cap',
    link: '/academics/ap',
  },
  {
    id: '2',
    name: 'International Baccalaureate (IB)',
    category: 'Advanced Academics',
    description: 'Rigorous international program developing critical thinking and global citizenship.',
    schools: ['Forsyth Central High School'],
    icon: 'globe',
    link: '/academics/ib',
  },
  {
    id: '3',
    name: 'STEM Academy',
    category: 'STEM',
    description: 'Specialized science, technology, engineering, and mathematics curriculum.',
    schools: ['All Schools'],
    icon: 'microscope',
    link: '/academics/stem',
  },
  {
    id: '4',
    name: 'Dual Enrollment',
    category: 'College Prep',
    description: 'Earn college credits while still in high school through partnerships with local colleges.',
    schools: ['All High Schools'],
    icon: 'book-open',
    link: '/academics/dual-enrollment',
  },
  {
    id: '5',
    name: 'Career & Technical Education',
    category: 'Career Pathways',
    description: 'Industry-certified programs preparing students for high-demand careers.',
    schools: ['All High Schools'],
    icon: 'wrench',
    link: '/academics/ctae',
  },
  {
    id: '6',
    name: 'Special Education',
    category: 'Support Services',
    description: 'Comprehensive services for students with diverse learning needs.',
    schools: ['All Schools'],
    icon: 'heart',
    link: '/academics/special-education',
  },
];

// Utility functions
export function getSchoolsByLevel(level: string): School[] {
  if (level === 'all') return schools;
  return schools.filter((school) => school.level === level);
}

export function getSchoolBySlug(slug: string): School | undefined {
  return schools.find((school) => school.slug === slug);
}

export function getFeaturedNews(): NewsArticle[] {
  return newsArticles.filter((article) => article.featured);
}

export function getNewsById(id: string): NewsArticle | undefined {
  return newsArticles.find((article) => article.id === id);
}

export function getUpcomingEvents(limit?: number): CalendarEvent[] {
  const now = new Date();
  const upcoming = calendarEvents
    .filter((event) => new Date(event.startDate) >= now)
    .sort((a, b) => new Date(a.startDate).getTime() - new Date(b.startDate).getTime());
  return limit ? upcoming.slice(0, limit) : upcoming;
}
